kind: pipeline
type: docker
name: build

steps:
  - name: build-image
    image: plugins/docker
    settings:
      repo: t3hn3rd/asuro-build
      tags: latest
      dockerfile: Dockerfile
      registry: docker.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: compile
    image: t3hn3rd/asuro-build:latest
    depends_on:
      - build-image
    commands:
      - ln -s /drone/src /code
      - find . -type f -print0 | xargs -0 dos2unix
      - chmod +x /code/*.sh