.after_script:
  script: 
    - chmod +x ./compile_check.sh
    - ./compile_check.sh $CI_JOB_STATUS
  artifacts:
    paths:
      - release/*.svg

stages:
  - chmod
  - compile_stub
  - vergen
  - compile_sources
  - link
  - isogen
  - finish

compile_stub:
  stage: compile_stub
  script: 
    - chmod +x ./compile_stub.sh
    - ./compile_stub.sh
  artifacts:
    paths:
      - lib/stub.o

vergen:
  stage: vergen
  script: 
    - chmod +x ./compile_vergen.sh
    - ./compile_vergen.sh
  artifacts:
    paths:
      - release/*.svg
      - src/include/asuro.pas

compile_sources:
  stage: compile_sources
  script:
    - chmod +x ./compile_sources.sh
    - ./compile_sources.sh
  artifacts:
    paths:
      - lib/*.o
  dependencies:
    - compile_stub
    - vergen

link:
  stage: link
  script:
    - chmod +x ./compile_link.sh
    - ./compile_link.sh
  artifacts:
    paths:
      - bin/kernel.bin
  dependencies:
    - compile_sources

isogen:
  stage: isogen
  script:
    - chmod +x ./compile_isogen.sh
    - ./compile_isogen.sh
  artifacts:
    paths:
      - ./Asuro.iso
  dependencies:
    - link

finish:
  stage: finish
  script: 
    - chmod +x ./compile_finish.sh
    - ./compile_finish.sh $CI_JOB_STATUS
  artifacts:
    paths:
      - release/build.svg
  dependencies:
    - isogen